spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/orders/**
                - Path=/orders

            - id: payment-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/payments/**
                - Path=/payments
